name: CI/CD Pipeline

# run this workflow on every push to the master branch
on:
  push:
    branches:
      - master

jobs:
  # this job runs all unit tests
  test: # <- test is the name of the job
    runs-on: ubuntu-latest # <- Specifies the host used to run the test
    strategy: # <- creates a build matrix, to execute this job on different versions
      matrix:
        node-version: [11.x, 12.x] # <- This job is first executed with node.js version 11 and then with version 12

    steps:
      # Checkout the complete repository
      - name: Checkout
        uses: actions/checkout@v1
      # first install all dependencies
      - name: Install dependencies
        run: npm install
      # run the jasmine unit tests
      - name: Test
        run: npm run unit-test
      # build the application to see if the build is successful
      - name: Build
        run: npm run build --prod

  # this job publishes the application on docker hub
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: m4nu3l99/dev-ops-final-assignment
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  # this job deploys the application on the heroku staging server
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: push to heroku
        env:
          HEROKU_REGISTRY_URL: registry.heroku.com
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
        run: |
          docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
          export HEROKU_API_KEY=$HEROKU_TOKEN
          heroku container:login
          heroku container:push web --app dev-ops-final-assignment
          heroku container:release web --app dev-ops-final-assignment
          heroku ps:scale web=1 --app dev-ops-final-assignment
