name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  test:
    # Specify the machine environment used to run the test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Try with node.js version 11 and 12
        node-version: [11.x, 12.x]

    steps:
      - uses: actions/checkout@v1

      # first install all dependencies
      - name: Install dependencies
        run: npm install
      # run the jasmine unit tests
      - name: Test
        run: npm run unit-test
      # build the application to see if the build is successful
      - name: Build
        run: npm run build --prod

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: m4nu3l99/dev-ops-final-assignment
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
